# Yarn Berry configuration for zero-installs
# Zero-installs means all packages are committed in .yarn/cache/
nodeLinker: node-modules

# Store packages in local .yarn/cache/ directory (not global cache)
enableGlobalCache: false

# Compression for cache files
compressionLevel: mixed
